"""PDF reporter — executive summary using reportlab."""

from __future__ import annotations

import datetime
from pathlib import Path
from typing import Optional

from laaf.core.stage_breaker import PSBResult


def _rl_available() -> bool:
    try:
        import reportlab  # noqa: F401
        return True
    except ImportError:
        return False


class PDFReporter:
    def generate(self, result: PSBResult, output_path: Path) -> Path:
        if not _rl_available():
            raise RuntimeError(
                "reportlab is required for PDF output. Install with: pip install reportlab"
            )
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            SimpleDocTemplate, Table, TableStyle, Paragraph,
            Spacer, HRFlowable,
        )

        output_path = output_path.with_suffix(".pdf")
        output_path.parent.mkdir(parents=True, exist_ok=True)

        doc = SimpleDocTemplate(str(output_path), pagesize=A4, topMargin=2*cm, bottomMargin=2*cm)
        styles = getSampleStyleSheet()
        navy = colors.HexColor("#1f3864")
        red = colors.HexColor("#c00000")

        title_style = ParagraphStyle("Title", parent=styles["Title"], textColor=navy, fontSize=18)
        h2_style = ParagraphStyle("H2", parent=styles["Heading2"], textColor=navy)
        body_style = styles["BodyText"]

        story = []

        # Title
        story.append(Paragraph("LAAF Security Assessment Report", title_style))
        story.append(Spacer(1, 6))
        story.append(Paragraph(
            f"Platform: <b>{result.platform}</b> | Model: <b>{result.model}</b> | "
            f"Date: {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            body_style,
        ))
        story.append(HRFlowable(width="100%", thickness=1, color=navy))
        story.append(Spacer(1, 12))

        # Executive Summary
        story.append(Paragraph("Executive Summary", h2_style))
        summary_data = [
            ["Metric", "Value"],
            ["Stages Broken", f"{result.stages_broken} / {len(result.stages)}"],
            ["Overall Breakthrough Rate", f"{result.overall_breakthrough_rate:.0%}"],
            ["Total Payloads Sent", str(result.total_attempts)],
            ["Total Duration", f"{result.total_duration_seconds:.1f}s"],
        ]
        summary_table = Table(summary_data, colWidths=[8*cm, 8*cm])
        summary_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), navy),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f5f5f5"), colors.white]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("PADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(summary_table)
        story.append(Spacer(1, 20))

        # Stage Details
        story.append(Paragraph("Stage Breakthrough Analysis", h2_style))
        stage_header = ["Stage", "Status", "Attempts", "Technique", "Category", "Confidence"]
        stage_data = [stage_header]
        for s in result.stages:
            stage_data.append([
                s.stage_id,
                "BROKEN" if s.broken else "RESISTANT",
                str(s.attempts),
                s.winning_payload.technique_id if s.winning_payload else "—",
                s.winning_payload.category if s.winning_payload else "—",
                f"{s.winning_confidence:.0%}",
            ])
        stage_table = Table(stage_data, colWidths=[2*cm, 2.5*cm, 2.5*cm, 3*cm, 3*cm, 3*cm])
        stage_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), navy),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f5f5f5"), colors.white]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(stage_table)
        story.append(Spacer(1, 20))

        # Footer note
        story.append(HRFlowable(width="100%", thickness=0.5, color=navy))
        story.append(Spacer(1, 6))
        story.append(Paragraph(
            "Generated by <b>LAAF v0.1.0</b> — Logic-layer Automated Attack Framework. "
            "Atta et al., Qorvex Research, 2026. For authorised security testing only.",
            ParagraphStyle("Footer", parent=body_style, fontSize=8, textColor=colors.grey),
        ))

        doc.build(story)
        return output_path
